---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Cluster'

Resources:

  EksInstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: eks-instance-access-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

Outputs:
  
  InstanceRole:
    Description: Name of role to assign to Ec2 to grant EKS access
    Value:
      Ref: EksInstanceRole
